# Generated by Django 2.2.4 on 2019-08-04 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogz', '0003_auto_20190804_1951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-publish',)},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='published',
            new_name='publish',
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=250, unique_for_date='publish'),
        ),
    ]
